### ISSUE TITLE
Cloud provide a global config param to indicating api delay?

### ISSUE THREAD

**Issue by zrb0001** [moqike/mock-server#2]
The global config param can accepted two type:
1. Number (eg: 1000, unit ms)
2. [nice to have] Range (eg: [1000, 2000]), that will apply a random delay time in range(1000 to 2000)

If api controller file has specified "delay" param, the global config should be override. in other words, the global delay config just apply for these controller which not specified delay param.

Thanks!

**Comment by siqiwith** [comment]
Implemented in v1.1.0
